if __name__ == "__main__":
    "# Bert-VITS2 数据预处理\n"
    "## 预先准备：\n"
    "下载 BERT 和 WavLM 模型：\n"
    "- [中文 RoBERTa](https://huggingface.co/hfl/chinese-roberta-wwm-ext-large)\n"
    "- [日文 DeBERTa](https://huggingface.co/ku-nlp/deberta-v2-large-japanese-char-wwm)\n"
    "- [英文 DeBERTa](https://huggingface.co/microsoft/deberta-v3-large)\n"
    "- [WavLM](https://huggingface.co/microsoft/wavlm-base-plus)\n"
    "\n"
    "将 BERT 模型放置到 `bert` 文件夹下，WavLM 模型放置到 `slm` 文件夹下，覆盖同名文件夹。\n"
    "\n"
    "数据准备：\n"
    "将数据放置在 data 文件夹下，按照如下结构组织：\n"
    "\n"
    "```\n"
    "├── data\n"
    "│   ├── {你的数据集名称}\n"
    "│   │   ├── esd.list\n"
    "│   │   ├── raw\n"
    "│   │   │   ├── ****.wav\n"
    "│   │   │   ├── ****.wav\n"
    "│   │   │   ├── ...\n"
    "```\n"
    "\n"
    "其中，`raw` 文件夹下保存所有的音频文件，`esd.list` 文件为标签文本，格式为\n"
    "\n"
    "```\n"
    "****.wav|{说话人名}|{语言 ID}|{标签文本}\n"
    "```\n"
    "\n"
    "例如：\n"
    "```\n"
    "vo_ABDLQ001_1_paimon_02.wav|派蒙|ZH|没什么没什么，只是平时他总是站在这里，有点奇怪而已。\n"
    "noa_501_0001.wav|NOA|JP|そうだね、油断しないのはとても大事なことだと思う\n"
    "Albedo_vo_ABDLQ002_4_albedo_01.wav|Albedo|EN|Who are you? Why did you alarm them?\n"
    "...\n"
    "```\n"
